project:
  type: website
  output-dir: docs

website:
  title: "Statistical Computing"
  navbar:
    left:
      - href: index.qmd

format:
  html:
    number-sections: false

execute:
  warning: false
  message: false